#!/bin/sh

# Assumes the following directory structure.
#   javasee/     => The top dir
#     lib/       => .jar file
#     bin/       => executable files

SCRIPT=`realpath $0`
TOPDIR="$( cd "$(dirname "$SCRIPT")/.."; pwd -P )"

if [ -z "$JAR_PATH" ]; then
  JAR_PATH=$TOPDIR/lib/JavaSee-all.jar
fi

java -Djavasee.name=javasee -jar $JAR_PATH "$@"
