name: Test

on:
  push:
    branches: ["master"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ["11", "12", "13", "14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew build
      - run: mkdir dist && tar -xvf build/distributions/JavaSee-bin-*.tar -C dist --strip-components 1
      - run: echo "${PWD}/dist/bin" >> $GITHUB_PATH
      - run: javasee version
      - run: javasee init
      - run: javasee test
      - run: javasee init -config test.yml
      - run: javasee test -config test.yml

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t javasee:dev .
      - run: docker run --rm -v "${PWD}:/work" -t javasee:dev version
      - run: docker run --rm -v "${PWD}:/work" -t javasee:dev init
      - run: docker run --rm -v "${PWD}:/work" -t javasee:dev test
