name: Test

on:
  push:
    branches: ["master"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ["11", "12", "13", "14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew shadowjar
      - run: ./gradlew test
      - run: scripts/javasee init -config test.yml
        env:
          JAR_PATH: build/libs/JavaSee-all.jar
      - run: scripts/javasee test -config test.yml
        env:
          JAR_PATH: build/libs/JavaSee-all.jar
